
#define UPBIT_ACCESS_KEY   ""
#define UPBIT_SECRET_KEY   ""

#define BINANCE_SPOT_ACCESS_KEY   ""
#define BINANCE_SPOT_SECRET_KEY   ""

#define BINANCE_FUTURES_ACCESS_KEY   ""
#define BINANCE_FUTURES_SECRET_KEY   ""